services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    container_name: nexus
    ports:
      - "8082:8081"
    volumes:
      - nexus-data:/nexus-data
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: "gitlab.elkanuco.lu"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.elkanuco.lu:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 22   # important!
    ports:
      - "8880:80"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: "256m"
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ./gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  centos:
    image: centos:7
    container_name: centos-container
    stdin_open: true # Equivalent to -i
    tty: true # Equivalent to -t
    privileged: true
    command: /usr/sbin/init # runs systemd
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    ports:
      - "8888:8080"
  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    container_name: ubuntu-container
    privileged: true
    tty: true # Equivalent to -t
    stdin_open: true # Equivalent to -i
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./data:/data
      - ./scripts:/scripts
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stop_signal: SIGRTMIN+3
    ports:
      - "8899:8080"

volumes:
  postgres_data:
  nexus-data:
  gitlab-data:
